
on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v1
      with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: '--prod'

        